# Generated by Django 4.0.10 on 2023-07-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64, verbose_name='Марка')),
                ('model', models.CharField(max_length=64, verbose_name='Модель')),
                ('date_create', models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата производства')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='HistoryCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_text', models.TextField(blank=True, null=True, verbose_name='Краткая история')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carsapp.car')),
            ],
        ),
        migrations.CreateModel(
            name='DetailCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cars', models.ManyToManyField(to='carsapp.car')),
            ],
        ),
    ]
