# Generated by Django 4.0.10 on 2023-07-06 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historycar',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsapp.car'),
        ),
    ]
