# Generated by Django 4.0.10 on 2023-07-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0002_rename_cars_car_alter_car_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=64, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_create',
            field=models.DateTimeField(verbose_name='Дата производства'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=64, verbose_name='Модель'),
        ),
    ]
