# Generated by Django 4.0.10 on 2023-07-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0004_alter_car_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_create',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата производства'),
        ),
    ]
